name: Cypress Tests

on: [push, workflow_dispatch]

jobs:

  cypress-electron-tests:

    runs-on: ubuntu-22.04
    steps:
      - name: Comentário
        run: |
          echo "Running Worflow ${{ github.event_name }}"
          
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Instalar as dependências
        run: yarn install

      - name: Executar testes E2E em Headless
        run: yarn cypress run
    
