name: Cypress Test Browser

on:
  push:
    branches: 
      - "main"

  workflow_dispatch:

jobs:

  cypress-tests:

    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
    strategy:
      matrix:
        navegador: [chrome, edge, electron]
    steps:
      - name: Comentário
        run: |
          echo "Running on ${{ github.event_name }} with browser ${{ matrix.navegador }}"
          
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: ${{ matrix.navegador }}
          record: false
          spec: cypress/e2e/*
