name: Cypress Tests

on: [push]

jobs:

  cypress-electron-tests:

    runs-on: ubuntu-lastest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Instalar as dependências
        run: yarn install

      - name: Executar testes E2E em Headless
        run: yarn cypress run
    
